# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSite', '0003_auto_20160617_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
