# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testSite', '0004_auto_20160617_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='count',
        ),
    ]
