# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSite', '0006_good_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='cnt',
            field=models.TextField(verbose_name='Количество'),
        ),
    ]
