# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSite', '0008_auto_20160617_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='cnt',
        ),
        migrations.AddField(
            model_name='good',
            name='amount_available',
            field=models.IntegerField(default=0, null=0, verbose_name='Количество в наличии'),
        ),
    ]
