# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSite', '0009_auto_20160617_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='miniaturefilename',
            field=models.CharField(default='favicon.ico', max_length=50, verbose_name='Имя файла миниатюры'),
        ),
    ]
