# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSite', '0011_good_miniature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='miniature',
            field=models.FilePathField(default='favicon.ico'),
        ),
    ]
