# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSite', '0015_auto_20160624_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
